server:
  port: 8080

#logging:
#  level: debug



netty:
  websocket:
    port: 8090
    # 绑定的网卡
    host: 127.0.0.1
    # 消息帧最大体积
    max-frame-size: 10240
    uri: websocket
    url: ws://127.0.0.1:8090/websocket